### ISSUE TITLE
Conflicting requirements with regard to minimum version of setuptools_scm ?

### ISSUE THREAD

**Issue by hartwork** [pycontribs/ansi2html#123]
Hello!

I noticed that https://github.com/pycontribs/ansi2html/blob/362961de1eae7c93a0299dff17848b6bece1a2a3/pyproject.toml#L4 asks for `setuptools_scm >=1.15.0` while https://github.com/pycontribs/ansi2html/blob/362961de1eae7c93a0299dff17848b6bece1a2a3/setup.py#L14 asks for `setuptools_scm >=3.5.0`. Is that intended? Which requirement is correct?

Thanks and best, Sebastian

**Comment by ssbarnea** [comment]
They are expected to be the same. I fixed https://github.com/pycontribs/ansi2html/pull/138

To answer your question, it depends on which tools and versions are used to build the package. Some will use one or another. The newest tools will use stuff inside `pyproject.toml`, the others are kept for backwards compatibility with older versions. Likely we will soon remove the setup.py completely.
