### ISSUE TITLE
[>=1.7.0a0] typing_extensions missing from requirements

### ISSUE THREAD

**Issue by nikluep-3ds** [pycontribs/ansi2html#180]
Hi!
I would like to use ansi2html on a machine running Python 3.7. However, I get the following crash:

```
Python 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ansi2html
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python37\lib\site-packages\ansi2html\__init__.py", line 1, in <module>
    from ansi2html.converter import Ansi2HTMLConverter
  File "C:\Program Files\Python37\lib\site-packages\ansi2html\converter.py", line 45, in <module>
    from typing_extensions import TypedDict
ModuleNotFoundError: No module named 'typing_extensions'
```

I guess the package is missing the dependency, for now I installed it manually. I don't have any experience regarding package setups, so I won't try to submit a fix, but at least wanted to mention it :)

**Comment by hartwork** [comment]
Confirming as a bug for Python <=3.7 since commit 0c1e1e8b7b8823b7c5e4de3d30dbbaccc05ae834. Seems like we need a python-version-specific entry in `setup.cfg` for PyPI package https://pypi.org/project/typing-extensions/ needs a version-conditional.
