### ISSUE TITLE
Copyright headers still refer to GPL

### ISSUE THREAD

**Issue by leifwalsh** [pycontribs/ansi2html#188]
In #72 you all got consensus to relicense this project under the LGPL v3, but the headers in the source code weren't updated. Could you update them and release a new package please, to resolve any ambiguity?

**Comment by leifwalsh** [comment]
The files that need updating still seem to be these: https://github.com/pycontribs/ansi2html/issues/72#issuecomment-972197028

**Comment by ssbarnea** [comment]
A PR to remove all headers would be appreviated.

**Comment by leifwalsh** [comment]
That fixes the headers, I could also change the PR to remove them. Sorry it took so long, my request for approval to contribute to this project got a bit lost and I forgot to follow up with them.
