### ISSUE TITLE
Project description in pyproject.toml (and on PyPI) is from ansible-lint rather than ansi2html

### ISSUE THREAD

**Issue by mtelka** [pycontribs/ansi2html#222]
The [ansi2html project page at PyPI](https://pypi.org/project/ansi2html/) is missing project description.  There is just _No project description provided_ line there.  Please add some reasonable project description for the project.  Thank you.

**Comment by hartwork** [comment]
There is "Convert text with ANSI color codes to HTML or to LaTeX." further down but you do have a point. Thanks for the report :+1:

**Comment by hartwork** [comment]
PS: I'm not yet sure how to fix this, only had a quick look so far. If anyone can help out with analysis or a pull request, that would be welcome. For a green CI basing on top of #221 may be a good or a bad idea, depending on view.

**Comment by mtelka** [comment]
But, OTOH, the current `description` looks strangely: **_Checks playbooks for practices and behavior that could potentially be improved_**.  Is it correct?

**Comment by hartwork** [comment]
@mtelka I found that…
- commit d076fa2112c8dea1e27d545d6a92b83c58498325 introduced the mismatch description,
- the source seems to be another RedHat project — ansible-lint — see https://github.com/ansible/ansible-lint/blob/8cd928126e15b175b50b91f9a068d1fc67b011ea/pyproject.toml#L14 ,
- Git tag v1.9.0rc1 is the only tag with the changes
- which matches the fact that https://pypi.org/project/ansi2html/1.8.0/ says `No project description provided` while https://pypi.org/project/ansi2html/1.9.0rc1/ says `Checks playbooks for practices and behavior that could potentially be improved`.

I have created pull request #223 to address the issue just now.

**Comment by ssbarnea** [comment]
Fixed in https://pypi.org/project/ansi2html/1.9.1/
