### ISSUE TITLE
It does not render exactly like in the terminal

### ISSUE THREAD

**Issue by docteurklein** [pycontribs/ansi2html#65]
I'm not sure if it's even really feasible at all, but here is an example:

Here's what it looks like in my terminal:

![shot](https://cloud.githubusercontent.com/assets/109846/15071821/e51c30ee-138e-11e6-9624-b661010e4973.png)

Here's the corresponding output once passed in ansi2html:

![shot](https://cloud.githubusercontent.com/assets/109846/15071830/f6db850a-138e-11e6-8354-2602d0f86288.png)

Here is the raw output:

https://gist.github.com/15467055821752207b566421a0ac664c

Any idea?

BTW, thanks for this fine lib. I love the solarized theme :)

**Comment by ralphbean** [comment]
Ooof.. I'd be glad to accept a patch to make this work, but I must confess I just don't have time (or sufficient interest) to dive into it myself.  :(

There could be some bug in the way we handle reset characters.  Maybe someone will come along and make this problem theirs to solve.  :)

**Comment by docteurklein** [comment]
@ralphbean thanks for the quick answer.
No prob, I totatlly understand. If I find anything, I'll try to make a PR.
Cheers!

**Comment by ralphbean** [comment]
(a thought -- may be related to #49 ?)

**Comment by ssbarnea** [comment]
That is true and it terminal behavior is outside its current scope. Feel free to look at https://github.com/willmcgugan/rich as an alternative for terminal heavy usage.
