### ISSUE TITLE
Consider adopting less restrictive licenses, like MPL

### ISSUE THREAD

**Issue by ssbarnea** [pycontribs/ansi2html#98]
Due to the current license which is incompatible with MPL, https://github.com/pytest-dev/pytest-html is not listing it as a dependency, which means it provides an ANSI-less experience by default.

Considering the size of the library, is there a rewrite needed for making it easier to consume by other open-source projects?

**Comment by ssbarnea** [comment]
@ralphbean ^

**Comment by ssbarnea** [comment]
To make the matter even works, apparently license headers in the source code mention GPL and not LGPL, see https://github.com/ralphbean/ansi2html/blob/develop/ansi2html/converter.py

Considering the size of this library maybe a full rewrite using MIT/MPL/BSD would be the easiest way to make it really re-usable by any other projects, without risks of affecting their own licensing.

**Comment by blueyed** [comment]
FWIW: according to https://github.com/pycontribs/ansi2html/issues/72#issuecomment-339054860 LGPL does not make a difference really compared to GPL.

**Comment by ssbarnea** [comment]
This seems to prove a real can of worms. Somehow I have the impression that even if we get everyone to agree on MIT license, we will still have one to troll us that he does not want it, even if his contribution may be close to null.

I am reopening it because but my expectations are low.

**Comment by ssbarnea** [comment]
The library is now using LGPL which is quite a liberal license that is compatible with most use cases.
